export const cities = [
  "Tucson",
  "Santa Clara",
  "Portland",
  "San Francisco",
  "New York",
  "Seattle",
  "Dallas",
  "Austin",
  "Chicago",
  "Los Angeles",
  "San Diego",
  "Denver",
  "San Jose",
  "Houston",
  "Miami",
  "Las Vegas",
  "Mountain View",
  "Phoenix"
];