[
  "Tucson",
  "Santa Clara",
  "Portland",
  "San Francisco",
  "New York",
  "Seattle",
  "Tucson",
  "Dallas",
  "Santa Clara",
  "Austin",
  "Seattle",
  "Chicago",
  "San Francisco",
  "Dallas",
  "Los Angeles",
  "Portland",
  "San Diego",
  "Denver",
  "San Diego",
  "Portland",
  "Seattle",
  "Chicago",
  "San Jose",
  "Seattle",
  "Dallas",
  "San Francisco",
  "San Jose",
  "Austin",
  "Dallas",
  "Austin",
  "New York",
  "Houston",
  "Miami",
  "Las Vegas",
  "Chicago",
  "Seattle",
  "Miami",
  "San Francisco",
  "Mountain View",
  "Austin",
  "Chicago",
  "Miami",
  "Miami",
  "Chicago",
  "Chicago",
  "Dallas",
  "Denver",
  "Denver",
  "Portland",
  "Seattle",
  "Tucson",
  "Chicago",
  "Las Vegas",
  "Houston",
  "San Diego",
  "Houston",
  "San Francisco",
  "Las Vegas",
  "Chicago",
  "Austin",
  "Los Angeles",
  "Santa Clara",
  "Los Angeles",
  "Santa Clara",
  "Portland",
  "San Francisco",
  "Chicago",
  "Miami",
  "Houston",
  "Dallas",
  "Seattle",
  "Denver",
  "Dallas",
  "Santa Clara",
  "Dallas",
  "Las Vegas",
  "Houston",
  "Chicago",
  "Mountain View",
  "New York",
  "San Francisco",
  "Dallas",
  "Santa Clara",
  "Phoenix",
  "Santa Clara",
  "Las Vegas",
  "San Jose",
  "Denver",
  "San Jose",
  "Los Angeles",
  "Santa Clara",
  "Mountain View",
  "Seattle",
  "New York",
  "Los Angeles",
  "Seattle",
  "Houston",
  "Dallas",
  "Austin",
  "San Jose",
  "Seattle",
  "Phoenix",
  "Seattle",
  "Santa Clara",
  "Seattle",
  "Dallas",
  "San Francisco",
  "San Jose",
  "Chicago",
  "Dallas",
  "Phoenix",
  "Portland",
  "Tucson",
  "Las Vegas",
  "Austin",
  "Denver",
  "New York",
  "Miami",
  "Mountain View",
  "Seattle",
  "Portland",
  "New York",
  "Santa Clara",
  "Las Vegas",
  "Mountain View",
  "Las Vegas",
  "San Francisco",
  "Dallas",
  "Denver",
  "Houston",
  "New York",
  "Santa Clara",
  "Phoenix",
  "Las Vegas",
  "Santa Clara",
  "Phoenix",
  "Seattle",
  "Denver",
  "Los Angeles",
  "Las Vegas",
  "Austin",
  "Dallas",
  "Miami",
  "San Francisco",
  "Las Vegas",
  "Las Vegas",
  "Dallas",
  "Mountain View",
  "Los Angeles",
  "Mountain View",
  "Mountain View",
  "Las Vegas",
  "Phoenix",
  "Tucson",
  "San Diego",
  "San Diego",
  "Tucson",
  "Los Angeles",
  "Denver",
  "Houston",
  "Phoenix",
  "Miami",
  "Portland",
  "San Francisco",
  "New York",
  "Las Vegas",
  "Los Angeles",
  "Houston",
  "Houston",
  "Seattle",
  "Mountain View",
  "Phoenix",
  "Mountain View",
  "Los Angeles",
  "Tucson",
  "Houston",
  "San Francisco",
  "Tucson",
  "Phoenix",
  "Denver",
  "Dallas",
  "Tucson",
  "Mountain View",
  "Santa Clara",
  "Tucson",
  "Denver",
  "Portland",
  "Miami",
  "San Jose",
  "Seattle",
  "Houston",
  "San Diego",
  "Santa Clara",
  "Los Angeles",
  "Tucson",
  "New York",
  "New York",
  "Miami",
  "Austin",
  "Santa Clara",
  "Mountain View",
  "Dallas",
  "Miami",
  "Mountain View",
  "Chicago",
  "Seattle",
  "New York",
  "Portland",
  "Chicago",
  "Mountain View",
  "Austin",
  "Phoenix",
  "Portland",
  "San Diego",
  "San Diego",
  "Houston",
  "Chicago",
  "Miami",
  "Chicago",
  "San Francisco",
  "Tucson",
  "Mountain View",
  "Los Angeles",
  "Chicago",
  "Los Angeles",
  "New York",
  "Santa Clara",
  "Los Angeles",
  "San Diego",
  "San Diego",
  "Dallas",
  "Denver",
  "San Diego",
  "Seattle",
  "Las Vegas",
  "Seattle",
  "Tucson",
  "Dallas",
  "Austin",
  "Chicago",
  "Houston",
  "Phoenix",
  "San Jose",
  "Las Vegas",
  "San Diego",
  "Austin",
  "Las Vegas",
  "Tucson",
  "Tucson",
  "Denver",
  "Portland",
  "Austin",
  "Denver",
  "San Diego",
  "Dallas",
  "San Francisco",
  "Los Angeles",
  "Dallas",
  "Santa Clara",
  "Portland",
  "Portland",
  "Santa Clara",
  "Denver",
  "Phoenix",
  "Las Vegas",
  "Santa Clara",
  "San Francisco",
  "Dallas",
  "Miami",
  "Austin",
  "Seattle",
  "Santa Clara",
  "Tucson",
  "Austin",
  "Portland",
  "Dallas",
  "San Jose",
  "Los Angeles",
  "San Francisco",
  "Chicago",
  "New York",
  "San Francisco",
  "Santa Clara",
  "Phoenix",
  "San Francisco",
  "Chicago",
  "Los Angeles",
  "Chicago",
  "Phoenix",
  "Denver",
  "Portland",
  "Los Angeles",
  "San Diego",
  "San Francisco",
  "Mountain View",
  "Santa Clara",
  "Seattle",
  "Mountain View",
  "San Francisco",
  "Miami",
  "Chicago",
  "Miami",
  "Houston",
  "Mountain View",
  "Denver",
  "Los Angeles",
  "San Francisco",
  "New York",
  "Las Vegas",
  "New York",
  "Dallas",
  "Los Angeles",
  "Santa Clara",
  "Las Vegas",
  "New York",
  "Tucson",
  "Phoenix",
  "Austin",
  "Seattle",
  "San Jose",
  "Los Angeles",
  "Austin",
  "Los Angeles",
  "Denver",
  "Houston",
  "San Diego",
  "Dallas",
  "Houston",
  "Austin",
  "Los Angeles",
  "Miami",
  "Houston",
  "Las Vegas",
  "Las Vegas",
  "Miami",
  "Seattle",
  "Dallas",
  "Las Vegas",
  "San Jose",
  "Los Angeles",
  "Portland",
  "Tucson",
  "Portland",
  "Houston",
  "Las Vegas",
  "San Francisco",
  "Las Vegas",
  "New York",
  "Austin",
  "Denver",
  "New York",
  "Tucson",
  "Dallas",
  "Miami",
  "Seattle",
  "San Francisco",
  "Santa Clara",
  "Miami",
  "Phoenix",
  "Mountain View",
  "Portland",
  "Portland",
  "Seattle",
  "Phoenix",
  "Austin",
  "Portland",
  "Austin",
  "Los Angeles",
  "Houston",
  "Dallas",
  "Santa Clara",
  "Las Vegas",
  "Houston",
  "Austin",
  "San Jose",
  "Santa Clara",
  "San Francisco",
  "New York",
  "Portland",
  "Dallas",
  "Mountain View",
  "Dallas",
  "San Francisco",
  "Seattle",
  "Los Angeles",
  "Seattle",
  "Mountain View",
  "New York",
  "Los Angeles",
  "Santa Clara",
  "New York",
  "New York",
  "Las Vegas",
  "Tucson",
  "Denver",
  "San Francisco",
  "Seattle",
  "Portland",
  "Chicago",
  "Miami"
]